# Lightweight pre-commit hooks for fast local development
repos:
  # Basic file quality (fast)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: detect-private-key  # Basic secret detection

  # Python formatting (fast)
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff lint
        entry: uv run ruff check --fix
        language: system
        types: [python]
        
      - id: ruff-format
        name: ruff format
        entry: uv run ruff format
        language: system
        types: [python]

# Note: Heavy security scans (GitLeaks, Bandit, etc.) run in CI
# This keeps local commits fast while ensuring security in PRs