# Job to add istio-injection labels to existing namespaces
apiVersion: batch/v1
kind: Job
metadata:
  name: add-istio-injection-labels
  namespace: istio-system
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: namespace-labeler
      restartPolicy: Never
      containers:
      - name: labeler
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          # Add istio-injection label to existing namespaces
          kubectl label namespace istio-gateway istio-injection=enabled --overwrite=true || true
          kubectl label namespace metallb-system istio-injection=disabled --overwrite=true || true
          echo "Namespace labels updated"
---
# ServiceAccount for the labeling job
apiVersion: v1
kind: ServiceAccount
metadata:
  name: namespace-labeler
  namespace: istio-system
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
---
# ClusterRole for namespace labeling
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-labeler
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "patch", "update"]
---
# ClusterRoleBinding for namespace labeling
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-labeler
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
subjects:
- kind: ServiceAccount
  name: namespace-labeler
  namespace: istio-system
roleRef:
  kind: ClusterRole
  name: namespace-labeler
  apiGroup: rbac.authorization.k8s.io