# Shared StorageClass for host-mounted persistent storage
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lamina-host-storage
  labels:
    {{- include "istio-config.labels" . | nindent 4 }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
reclaimPolicy: Retain