# Default values for monitoring stack
namespace: monitoring

prometheus:
  enabled: true
  image:
    repository: prom/prometheus
    tag: v2.45.0
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  retention: 7d
  scrapeInterval: 30s
  persistence:
    enabled: true
    size: 50Gi

loki:
  enabled: true
  image:
    repository: grafana/loki
    tag: 2.9.0
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  persistence:
    enabled: true
    size: 50Gi

vector:
  enabled: true
  image:
    repository: timberio/vector
    tag: 0.34.0-alpine
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

grafana:
  enabled: true
  image:
    repository: grafana/grafana
    tag: 10.0.0
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  # adminPassword will be generated or provided via secret
  existingSecret: ""
  secretKey: "admin-password"
  service:
    type: ClusterIP
    port: 3000
  persistence:
    enabled: true
    size: 10Gi

kubeStateMetrics:
  enabled: true
  image:
    repository: registry.k8s.io/kube-state-metrics/kube-state-metrics
    tag: v2.10.0
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

# Ingress configuration for external access
ingress:
  enabled: true
  className: ""
  annotations: {}
    # nginx.ingress.kubernetes.io/rewrite-target: /
  
  grafana:
    host: grafana.local
    path: /
    pathType: Prefix
  
  prometheus:
    host: prometheus.local
    path: /
    pathType: Prefix
  
  tls: false
  secretName: ""

# Service exposure configuration
serviceExposure:
  # All traffic goes through Istio gateway
  type: ClusterIP
