# Jaeger All-in-One for distributed tracing
{{- if .Values.jaeger.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: observability
  labels:
    app: jaeger
  annotations:
    # Force rolling update when config changes
    deployment.kubernetes.io/revision: "{{ .Release.Revision }}"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
      annotations:
        # Force pod restart on config change
        checksum/config: {{ .Values | toYaml | sha256sum }}
    spec:
      containers:
      - name: jaeger
        image: {{ .Values.jaeger.allInOne.image }}
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        - containerPort: 5778
          protocol: TCP
        - containerPort: 16686
          protocol: TCP
        - containerPort: 14250
          protocol: TCP
        - containerPort: 14268
          protocol: TCP
        - containerPort: 14269
          protocol: TCP
        - containerPort: 4317
          protocol: TCP
        - containerPort: 4318
          protocol: TCP
        env:
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
        - name: COLLECTOR_ZIPKIN_HOST_PORT
          value: ":9411"
        - name: MEMORY_MAX_TRACES
          value: "50000"
        - name: LOG_LEVEL
          value: "info"
        resources:
{{ toYaml .Values.jaeger.allInOne.resources | indent 10 }}
        livenessProbe:
          httpGet:
            path: /
            port: 14269
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 14269
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: observability
  labels:
    app: jaeger
spec:
  type: {{ .Values.jaeger.allInOne.service.type }}
  selector:
    app: jaeger
  ports:
  - name: query-http
    port: {{ index .Values.jaeger.allInOne.service.ports 0 "port" }}
    targetPort: {{ index .Values.jaeger.allInOne.service.ports 0 "targetPort" }}
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: observability
  labels:
    app: jaeger
spec:
  type: ClusterIP
  selector:
    app: jaeger
  ports:
  - name: grpc
    port: {{ index .Values.jaeger.allInOne.service.ports 1 "port" }}
    targetPort: {{ index .Values.jaeger.allInOne.service.ports 1 "targetPort" }}
    protocol: TCP
  - name: http
    port: {{ index .Values.jaeger.allInOne.service.ports 2 "port" }}
    targetPort: {{ index .Values.jaeger.allInOne.service.ports 2 "targetPort" }}
    protocol: TCP
  - name: zipkin
    port: 9411
    targetPort: 9411
    protocol: TCP
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
    protocol: TCP
  - name: otlp-http
    port: 4318
    targetPort: 4318
    protocol: TCP
{{- end }}