{{- if index .Values.services "lamina-llm-serve" "enabled" }}
apiVersion: v1
kind: Service
metadata:
  name: lamina-llm-serve
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "lamina.labels" . | nindent 4 }}
    app.kubernetes.io/component: lamina-llm-serve
spec:
  type: {{ index .Values.services "lamina-llm-serve" "service" "type" }}
  ports:
  {{- range index .Values.services "lamina-llm-serve" "service" "ports" }}
  - port: {{ . }}
    targetPort: {{ . }}
    protocol: TCP
  {{- end }}
  selector:
    {{- include "lamina.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: lamina-llm-serve
{{- end }}
