# Default values for service-mesh template
# These can be overridden by target-specific values

# Chart naming
nameOverride: ""
fullnameOverride: ""

# Mesh configuration
mesh:
  traffic:
    destinationRule:
      trafficPolicy:
        tls:
          mode: ISTIO_MUTUAL
  mtls:
    mode: STRICT

# Service mesh settings
serviceMesh:
  circuitBreaker:
    consecutiveErrors: 5
    interval: 30s
    baseEjectionTime: 30s
    maxEjectionPercent: 50

# Gateway configuration
gateway:
  enabled: true
  name: lamina-gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "*"
      tls:
        mode: SIMPLE
        credentialName: lamina-tls-cert

# Security configuration
security:
  peerAuthentication:
    default:
      mtls:
        mode: STRICT

# mTLS configuration (legacy - kept for backward compatibility)
mtls:
  mode: STRICT
  
# Virtual Service routing (hostname-based)
virtualService:
  services:
    grafana:
      enabled: true
      hostname: grafana.lamina.local
      service: grafana.monitoring.svc.cluster.local
      port: 3000
    prometheus:
      enabled: true
      hostname: prometheus.lamina.local
      service: prometheus.monitoring.svc.cluster.local
      port: 9090
    jaeger:
      enabled: true
      hostname: jaeger.lamina.local
      service: jaeger-query.observability.svc.cluster.local
      port: 16686
    kiali:
      enabled: true
      hostname: kiali.lamina.local
      service: kiali.observability.svc.cluster.local
      port: 20001
    lamina-core:
      enabled: true
      hostname: core.lamina.local
      service: lamina-core.lamina-system.svc.cluster.local
      port: 8080

# Telemetry configuration
telemetry:
  enabled: true
  metrics: true
  accessLogs:
    enabled: true