# MetalLB Configuration for Mac Production
namespace: metallb-system

# Controller configuration
controller:
  image:
    repository: quay.io/metallb/controller
    tag: v0.14.3
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 200Mi

# Speaker configuration (Layer 2 mode)
speaker:
  image:
    repository: quay.io/metallb/speaker
    tag: v0.14.3
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 200Mi
  # Layer 2 configuration
  frr:
    enabled: false  # Not needed for L2 mode

# IP Address Pool for LoadBalancer services
# Using Colima's bridge network range
ipAddressPool:
  name: production-pool
  addresses:
    # Colima production VM uses 192.168.5.0/24 network
    # Reserving .240-.250 for LoadBalancer IPs
    - 192.168.5.240-192.168.5.250

# L2 Advertisement
l2Advertisement:
  name: production-l2
  interfaces: []  # Advertise on all interfaces

# Prometheus metrics
prometheus:
  enabled: true
  serviceMonitor:
    enabled: false  # Enable if using Prometheus Operator

# Security settings
securityContext:
  runAsNonRoot: true
  runAsUser: 65534
  fsGroup: 65534