# Default Destination Rules for mTLS and traffic policies
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: default-mtls
  namespace: istio-system
spec:
  host: "*.local"
  trafficPolicy:
    tls:
      mode: {{ .Values.mesh.traffic.destinationRule.trafficPolicy.tls.mode }}
    connectionPool:
      tcp:
        maxConnections: 50
      http:
        http1MaxPendingRequests: 100
        maxRequestsPerConnection: 10
    outlierDetection:
      consecutive5xxErrors: {{ .Values.serviceMesh.circuitBreaker.consecutiveErrors }}
      interval: {{ .Values.serviceMesh.circuitBreaker.interval }}
      baseEjectionTime: {{ .Values.serviceMesh.circuitBreaker.baseEjectionTime }}
      maxEjectionPercent: {{ .Values.serviceMesh.circuitBreaker.maxEjectionPercent }}

---
# Destination rule for Lamina services
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: lamina-services
  namespace: lamina-system
spec:
  host: "*.lamina-system.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: {{ .Values.mesh.traffic.destinationRule.trafficPolicy.tls.mode }}
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 200
        maxRequestsPerConnection: 20
    outlierDetection:
      consecutive5xxErrors: {{ .Values.serviceMesh.circuitBreaker.consecutiveErrors }}
      interval: {{ .Values.serviceMesh.circuitBreaker.interval }}
      baseEjectionTime: {{ .Values.serviceMesh.circuitBreaker.baseEjectionTime }}
      maxEjectionPercent: {{ .Values.serviceMesh.circuitBreaker.maxEjectionPercent }}
  subsets:
  - name: v1
    labels:
      version: v1
  - name: canary
    labels:
      version: canary

---
# Destination rule for observability services
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: observability-services
  namespace: observability
spec:
  host: "*.observability.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: {{ .Values.mesh.traffic.destinationRule.trafficPolicy.tls.mode }}
    connectionPool:
      tcp:
        maxConnections: 50
      http:
        http1MaxPendingRequests: 100
        maxRequestsPerConnection: 10

---
# Destination rule for monitoring services
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: monitoring-services
  namespace: monitoring
spec:
  host: "*.monitoring.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: {{ .Values.mesh.traffic.destinationRule.trafficPolicy.tls.mode }}
    connectionPool:
      tcp:
        maxConnections: 50
      http:
        http1MaxPendingRequests: 100
        maxRequestsPerConnection: 10

---
# Destination rule for lamina-dashboard services
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: lamina-dashboard-services
  namespace: lamina-dashboard
spec:
  host: "*.lamina-dashboard.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: {{ .Values.mesh.traffic.destinationRule.trafficPolicy.tls.mode }}
    connectionPool:
      tcp:
        maxConnections: 50
      http:
        http1MaxPendingRequests: 100
        maxRequestsPerConnection: 10

---
# Kubernetes API server requires special handling (not part of mesh)
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: kubernetes-api-server
  namespace: istio-system
spec:
  host: kubernetes.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE  # API server is external to mesh