# Main Lamina Gateway for external traffic
{{- if .Values.gateway.enabled }}
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: istio-system
spec:
  selector:
    istio: gateway
  servers:
  {{- range .Values.gateway.servers }}
  - port:
      number: {{ .port.number }}
      name: {{ .port.name }}
      protocol: {{ .port.protocol }}
    hosts:
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
    {{- if .tls }}
    tls:
      mode: {{ .tls.mode }}
      {{- if .tls.credentialName }}
      credentialName: {{ .tls.credentialName }}
      {{- end }}
    {{- end }}
  {{- end }}

---
# Grafana VirtualService with HTTPS redirect
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: grafana-vs
  namespace: istio-system
spec:
  hosts:
  - grafana.lamina.local
  gateways:
  - {{ .Values.gateway.name }}
  http:
  {{- if .Values.gateway.httpsOnly }}
  # Redirect HTTP to HTTPS
  - match:
    - headers:
        ":scheme":
          exact: http
    redirect:
      scheme: https
      redirectCode: 301
  {{- end }}
  # HTTPS traffic routing
  - route:
    - destination:
        host: grafana.monitoring.svc.cluster.local
        port:
          number: 3000

---
# Prometheus VirtualService with HTTPS redirect
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: prometheus-vs
  namespace: istio-system
spec:
  hosts:
  - prometheus.lamina.local
  gateways:
  - {{ .Values.gateway.name }}
  http:
  {{- if .Values.gateway.httpsOnly }}
  - match:
    - headers:
        ":scheme":
          exact: http
    redirect:
      scheme: https
      redirectCode: 301
  {{- end }}
  - route:
    - destination:
        host: prometheus.monitoring.svc.cluster.local
        port:
          number: 9090

---
# Jaeger VirtualService with HTTPS redirect
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: jaeger-vs
  namespace: istio-system
spec:
  hosts:
  - jaeger.lamina.local
  gateways:
  - {{ .Values.gateway.name }}
  http:
  {{- if .Values.gateway.httpsOnly }}
  - match:
    - headers:
        ":scheme":
          exact: http
    redirect:
      scheme: https
      redirectCode: 301
  {{- end }}
  - route:
    - destination:
        host: jaeger-query.observability.svc.cluster.local
        port:
          number: 16686

---
# Kiali VirtualService with HTTPS redirect
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kiali-vs
  namespace: istio-system
spec:
  hosts:
  - kiali.lamina.local
  gateways:
  - {{ .Values.gateway.name }}
  http:
  {{- if .Values.gateway.httpsOnly }}
  - match:
    - headers:
        ":scheme":
          exact: http
    redirect:
      scheme: https
      redirectCode: 301
  {{- end }}
  - route:
    - destination:
        host: kiali.observability.svc.cluster.local
        port:
          number: 20001

---
# Lamina Core VirtualService with HTTPS redirect
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: lamina-core-vs
  namespace: istio-system
spec:
  hosts:
  - core.lamina.local
  gateways:
  - {{ .Values.gateway.name }}
  http:
  {{- if .Values.gateway.httpsOnly }}
  - match:
    - headers:
        ":scheme":
          exact: http
    redirect:
      scheme: https
      redirectCode: 301
  {{- end }}
  - route:
    - destination:
        host: lamina-core.lamina-system.svc.cluster.local
        port:
          number: 8080

---
# Lamina Dashboard VirtualService with HTTPS redirect
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: lamina-dashboard-vs
  namespace: istio-system
spec:
  hosts:
  - dashboard.lamina.local
  gateways:
  - {{ .Values.gateway.name }}
  http:
  {{- if .Values.gateway.httpsOnly }}
  - match:
    - headers:
        ":scheme":
          exact: http
    redirect:
      scheme: https
      redirectCode: 301
  {{- end }}
  - route:
    - destination:
        host: lamina-dashboard.lamina-dashboard.svc.cluster.local
        port:
          number: 5001

{{- end }}