apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lamina-llm-serve.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lamina-llm-serve.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "lamina-llm-serve.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lamina-llm-serve.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        env:
        {{- toYaml .Values.env | nindent 8 }}
        - name: UV_CACHE_DIR
          value: "/tmp/.uv-cache"
        - name: UV_NO_CACHE
          value: "1"
        volumeMounts:
        - name: models-config
          mountPath: /app/models.yaml
          subPath: models.yaml
        - name: models-storage
          mountPath: /app/models
        {{- if .Values.healthCheck.enabled }}
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: {{ .Values.healthCheck.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthCheck.periodSeconds }}
          timeoutSeconds: {{ .Values.healthCheck.timeoutSeconds }}
          failureThreshold: {{ .Values.healthCheck.failureThreshold }}
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: {{ .Values.healthCheck.timeoutSeconds }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      volumes:
      - name: models-config
        configMap:
          name: {{ include "lamina-llm-serve.fullname" . }}-config
      - name: models-storage
        {{- if .Values.models.storage }}
        persistentVolumeClaim:
          claimName: {{ include "lamina-llm-serve.fullname" . }}-models-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
