version: '3.8'

services:
  test-llm:
    image: ollama/ollama:latest
    container_name: lamina-test-llm
    ports:
      - "11435:11434"  # Different port to avoid conflicts
    volumes:
      - ./test-llm-models:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - test-network

networks:
  test-network:
    driver: bridge