# Colima configuration for production environment
# This provides declarative port forwarding from VM to host

# VM resources
cpu: 16
memory: 256
disk: 500

# Runtime
runtime: docker

# Architecture
arch: aarch64

# Mounts
mounts:
  - location: /tmp/lamina-models
    writable: true
mountType: virtiofs

# Port forwarding from VM to host
# This makes NodePort services accessible from Mac
portForwards:
  # Grafana
  - guestPort: 30300
    hostPort: 30300
    protocol: tcp
  # Prometheus  
  - guestPort: 30900
    hostPort: 30900
    protocol: tcp
  # Future services can be added here
  # Lamina Core API
  - guestPort: 30080
    hostPort: 30080
    protocol: tcp
  # Lamina LLM Serve
  - guestPort: 30081
    hostPort: 30081
    protocol: tcp

# Kubernetes
kubernetes:
  enabled: false  # We install k3s separately

# Network
network:
  address: true
  dns:
    - 8.8.8.8
    - 8.8.4.4