# ChromaDB authentication secret
---
apiVersion: v1
kind: Secret
metadata:
  name: chromadb-secret
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: chromadb-secret
    app.kubernetes.io/component: security
    app.kubernetes.io/part-of: lamina-os
type: Opaque
data:
  # Base64 encoded ChromaDB token - should be generated/rotated regularly
  # Default token: lamina_chroma_token_production_change_me
  token: {{ .Values.chromadb.auth.token | default "bGFtaW5hX2Nocm9tYV90b2tlbl9wcm9kdWN0aW9uX2NoYW5nZV9tZQ==" | quote }}
stringData:
  # Plain text version for debugging (remove in production)
  {{- if .Values.chromadb.auth.debug }}
  token-plain: {{ .Values.chromadb.auth.tokenPlain | default "lamina_chroma_token_production_change_me" | quote }}
  {{- end }}