{{- if .Values.models.storage }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "lamina-llm-serve.fullname" . }}-models-pv
  labels:
    {{- include "lamina-llm-serve.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.models.storage.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # Keep data when PVC is deleted
  storageClassName: {{ .Values.models.storage.storageClass | default "lamina-host-storage" }}
  hostPath:
    path: /lamina-data/models
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ index .Values.nodeSelector "kubernetes.io/hostname" | default "colima-production" }}
# Note: StorageClass is created by istio-config chart to avoid duplication
{{- end }}