name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: uv sync --extra dev
    
    - name: Lint with ruff
      run: uv run ruff check
    
    - name: Format check with black
      run: uv run black --check .
    
    - name: Type check with mypy
      run: uv run mypy packages/
    
    - name: Security check with bandit
      run: uv run bandit -r packages/
    
    - name: Test with pytest
      run: uv run pytest --cov=packages --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  package-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ["lamina-core", "lamina-llm-serve"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    
    - name: Set up Python
      run: uv python install 3.13
    
    - name: Test package in isolation
      run: |
        cd packages/${{ matrix.package }}
        uv sync
        uv run pytest

  build:
    runs-on: ubuntu-latest
    needs: [test, package-tests]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    
    - name: Set up Python
      run: uv python install 3.13
    
    - name: Build packages
      run: |
        cd packages/lamina-core
        uv build
        cd ../lamina-llm-serve  
        uv build
    
    - name: Check package metadata
      run: |
        uv run twine check packages/*/dist/*